# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Gaussian Kernel Nonparametric Conditional Expectation
#'
#' This calculates the Gaussian kernel nonparametric conditional expectation
#' for given data points using \code{Rcpp} with \code{OpenMP}.
#'
#' @param Y A numeric vector of outcome variable
#' @param X A numeric vector or matrix of explanatory variable(s)
#' @param args A numeric vector or matrix of arguments at which nonparametric conditional
#' expectations are calculated
#' @param H A numeric vector of bandwidth(s)
#' @param n_cores the number of threads to parallize the computation of nonparametric
#' conditional expectation over \code{args}
#' @export
#' @return A numeric vector of nonparametric conditional estimates evaluated at \code{args}
#' @useDynLib semiBRM, .registration = TRUE
#' @importFrom Rcpp evalCpp
GaussianKerNonpar <- function(Y, X, args, H, n_cores = 3L) {
    .Call(`_semiBRM_GaussianKerNonpar`, Y, X, args, H, n_cores)
}

#' Leave-One-Out Gaussian Kernel Nonparametric Conditional Expectation
#'
#' This calculates the leave-one-out Gaussian kernel nonparametric conditional
#' expectation over data points of explanatory variables using \code{Rcpp} with \code{OpenMP}.
#'
#' @param Y A numeric vector of outcome variable
#' @param X A numeric vector or matrix of explanatory variable(s)
#' @param H A numeric vector of bandwidth(s)
#' @param n_cores the number of threads to parallize the computation of nonparametric
#' conditional expectation over \code{X}
#' @export
#' @return A numeric vector of leave-one-out nonparametric conditional estimates evaluated at \code{X}
#' @useDynLib semiBRM, .registration = TRUE
#' @importFrom Rcpp evalCpp
GaussianKerNonparLeaveOneOut <- function(Y, X, H, n_cores = 3L) {
    .Call(`_semiBRM_GaussianKerNonparLeaveOneOut`, Y, X, H, n_cores)
}

